name: ci

on:
  schedule:
    # every 09:31 UTC
    - cron: "31 09 * * *"
    # every 21:31 UTC
    - cron: "31 21 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      KEY: ${{ secrets.KEY }}
      REPO: ${{ secrets.REPO }}
    steps:
      - name: pull
        uses: actions/checkout@v4
      - name: run
        run: |
          bash ./run.sh
